(#4) Создан сервис для конфигурации объекта погоды
StayInLight/react-weather-app pull request #18
Opened 2020-10-09 15:35 UTC by denkhis

2020-10-10 05:53 UTC, Karambirov requested changes

2020-10-10 05:53 UTC, karambirov commented on src/services/weather-app-service.js
> +export default class WeatherAppService extends NetworkingService {
Нужно уйти от наследования и передавать `NetworkingService` через конструктор

2020-10-10 05:53 UTC, karambirov commented on src/services/weather-app-service.js
> +  configureWeatherObject(cityName) {
Метод бизнес-логики не должен что-то настраивать. На этом слое мы должны рассуждать только в терминах реального мира, например, 
```javascript
getWeatherForToday(cityName)
```

2020-10-10 05:54 UTC, Karambirov commented on src/services/weather-app-service.js
> +export default class WeatherAppService extends NetworkingService {
Обсуди это с @StayInLight, он уже начал работать над этим.
+ в чате скинул почитать про Dependency Injection, изучи

2020-10-10 21:11 UTC, StayInLight requested changes

2020-10-10 21:11 UTC, tirakhimov commented on src/services/weather-app-service.js
> +weatherAppService.configureWeatherObject('London');
Я полагаю, ты использовал это для тестирования. Но в main такое пушить нельзя.

2020-10-10 21:11 UTC, tirakhimov commented on src/services/weather-app-service.js
> +      console.log(weatherObj);
Здесь такая же проблема, как и на строчках 18 19.

2020-10-11 12:09 UTC, closed without merging

2020-10-11 12:10 UTC, denkhis commented
Закрыл PR, т.к. @StayInLight уже сделал PR с актуальными исправлениями.