(#4) Рефакторинг сервиса weather-app
StayInLight/react-weather-app pull request #21
Opened 2020-10-10 21:16 UTC by StayInLight

- [ ] Исправил ошибку в методе getWeatherInfo
- [ ] Компонент weather-card отображает данные, полученные с сервера

2020-10-10 21:27 UTC, denkhis requested changes

2020-10-10 21:27 UTC, denkhis commented on src/services/weather-service.js
> +        sky: `${weatherName}`,
Переименовать ключ `sky` в `weatherName`

2020-10-10 21:31 UTC, denkhis requested changes

2020-10-10 21:31 UTC, denkhis commented on src/components/weather-card/weaher-card.js
> +          sky: response.sky,
Переименовать поле `sky` в `weatherName`

2020-10-11 14:22 UTC, Karambirov requested changes

2020-10-11 14:22 UTC, karambirov commented on src/components/weather-card/weaher-card.js
> +  state ={}
После `=` нужен пробел

2020-10-11 14:22 UTC, karambirov commented on src/components/weather-card/weaher-card.js
> +  weatherService = new WeatherService()
Вообще надо сервис в компонент передавать через конструктор, а не создавать жесткую зависимость внутри, иначе мы это просто не сможем протестировать потом

2020-10-11 14:22 UTC, Karambirov commented on src/helpers.js
> +}
За такое решение лайк 👍🏻

2020-10-11 14:22 UTC, Karambirov commented on src/index.js
> -  </React.StrictMode>,
Почему убрали `StrictMode`?

2020-10-11 14:22 UTC, Karambirov commented on src/services/networking-service.js
>    async getWeatherInfo(cityName) {
Слово `Info` в названии метода выглядит лишним. Я бы назвал `getWeather(cityName)`

2020-10-11 14:22 UTC, Karambirov commented on src/services/networking-service.js
>    async getWeatherInfo(cityName) {
А вот то, что используется `getWeather` вместо `fetchWeather` – это очень хорошо. Из названия становится понятно, какой HTTP метод используется в `NetworkingService` 👍🏻

2020-10-11 14:22 UTC, Karambirov commented on src/helpers.js
> +}
Но нельзя создавать всякие непонятные файлы типа `helpers`, `utils` и т.п. У всего должно быть своё место, а такие файлы обычно просто помойки.

Я вижу два решения:

1. Добавить этот метод как расширения самого типа строки в новом файле `string.js`:
```javascript
String.prototype.capitalize = function() {
  return this.charAt(0).toUpperCase() + this.slice(1)
}
```

2. Использовать CSS, чтобы сделать букву заглавной в презентационной части:
```css
p.capitalize {
  text-transform: capitalize;
}
```
Очевидно, что нужно использовать правильный селектор, а не как в моем примере. Тут я лишь хочу подчеркнуть, что нам капитализация нужна только для отображения, никакая логика на этом не завязана, поэтому странно, что в `WeatherService` происходит трансформация строки при формировании объекта, на мой взгляд.

2020-10-11 14:22 UTC, Karambirov commented on src/components/weather-card/weaher-card.js
> +            Погода в {cityName}
Если решишь использовать метод `capitalize`, то надо делать это здесь, а не при создании объекта.
Потому что именно здесь мы форматируем данные для корректного отображения. В `WeatherService` мы работаем только с данными.

2020-10-11 14:22 UTC, Karambirov commented on src/services/weather-service.js
> +  networkingService = new NetworkingService()
Здесь тоже надо передавать `NetworkingService` снаружи

2020-10-11 15:10 UTC, StayInLight commented on src/index.js
> -  </React.StrictMode>,
При использовании `StrictMode` запрос к сети делался дважды, я полагаю, что это как-то связано с `ServiceWorkers`, которые мы не используем в нашем проекте

2020-10-12 06:10 UTC, Karambirov approved these changes

2020-10-12 10:12 UTC, denkhis approved these changes

2020-10-12 10:12 UTC, merged