Добавлен сервис для отображения текущей даты
StayInLight/react-weather-app pull request #24
Opened 2020-10-11 19:09 UTC by denkhis

### Что сделано 

- Добавлен сервис для конфигурации текущей даты
- Добавлен компонент даты

2020-10-11 19:18 UTC, StayInLight requested changes

2020-10-11 19:18 UTC, StayInLight commented on src/components/date/date.js
> +}
Назови компонент current-date

2020-10-11 19:18 UTC, StayInLight commented on src/services/date-formatter.js
> +  monthsArray = ['Января', 'Февраля', 'Марта', 'Апреля', 'Мая', 'Июня', 'Июля', 'Августа', 'Сентября', 'Октября', 'Ноября', 'Декабря'];
Не используй слово array, и так понятно, что массив

2020-10-11 19:18 UTC, StayInLight commented on src/components/date/date.js
> +export default function Date() {
и функцию тоже current-date

2020-10-11 19:18 UTC, StayInLight commented on src/services/date-formatter.js
> +    const dateObject = this.configureDate();
Деструктуризируй объект dateObject(назови просто date, мы понимаем, что это объект) и в return напиши более читаемый код

2020-10-11 19:24 UTC, Karambirov commented on src/services/date-formatter.js
> +  monthsArray = ['Января', 'Февраля', 'Марта', 'Апреля', 'Мая', 'Июня', 'Июля', 'Августа', 'Сентября', 'Октября', 'Ноября', 'Декабря'];
Не согласен. JS не типизирован, поэтому названия типов в конце помогают понять, как с этим работать.

Даже в iOS на строго типизированном Swift мы пишем `loginButton`, `emailTextField` и т.п.

2020-10-11 19:31 UTC, Karambirov requested changes

2020-10-11 19:31 UTC, Karambirov commented on src/components/date/date.css
> +    padding-top: 13px;
Какой-то странный отступ. Обычно отступы должны делиться на 2. 
Может сделаем 12? Или в этом есть какой-то замысел?

2020-10-11 19:31 UTC, Karambirov commented on src/components/date/date.js
> +}
Ты же имеешь в виду название файла и то, что написано на строчке с `export`?

2020-10-11 19:41 UTC, denkhis commented on src/components/date/date.css
> +    padding-top: 13px;
уже пофиксил в настройках, для css в вебшторме почему-то по дефолту стоял 4 отступ

2020-10-11 19:45 UTC, Karambirov requested changes

2020-10-11 19:45 UTC, Karambirov commented on src/services/date-formatter.js
> +  configureDate() {
Вообще принято называть методы, которые создают что-то, со словом make. В данном случае правильнее будет `makeDate()`.

Configure стоит использовать тогда, когда у тебя уже есть какой-то созданный объект и ты хочешь его настроить.

2020-10-11 19:45 UTC, Karambirov commented on src/services/date-formatter.js
> +  configureDate() {
А ещё этот метод никогда не будет использован публично (т.е. за пределами этого форматтера). Поэтому его нужно сделать **приватным**.

Насколько я понимаю, в JS нет ключевого слова, указывающего на приватность и ограничивающего использование из вне.

Как я видел, чтобы достичь такого эффекта, метод, который хотят сделать приватным, создают внутри публичного. 

Поэтому здесь можно попробовать или просто сам метод перенести внутрь `formatDate()`, или же вообще просто сразу перенести создание этого объекта в тот метод, не создавая отдельный метод внутри.

2020-10-12 06:13 UTC, Karambirov commented on src/components/date/date.css
> +    padding-top: 13px;
Я имею в виду, что не может быть `padding-top` равен 13 px. Это странно и вряд ли симметрично. Обычно делают или 12, или 14

2020-10-12 06:19 UTC, Karambirov requested changes

2020-10-12 06:19 UTC, Karambirov commented on src/services/date-formatter.js
> +    return `${dayOfWeek}, ${currentDate} ${currentMonth} ${hour}:${minutes}`;
Здесь идет `день недели` потом `текущая дата`, `месяц`, `час`, `минуты`.
Вопрос: что такое `текущая дата`? 
Приведи пример отформатированного текста. Как будет выглядеть вся возвращаемая строка?

2020-10-12 06:19 UTC, Karambirov commented on src/components/current-date/current-date.css
> +  padding-top: 13px;
Как я уже и сказал, `padding-top` должен быть четным числом

2020-10-12 07:34 UTC, denkhis commented on src/services/date-formatter.js
> +    return `${dayOfWeek}, ${currentDate} ${currentMonth} ${hour}:${minutes}`;
Понедельник, 12 октября 10:30

Вероятно, корректнее будет назвать переменную dayOfMonth, чтобы было понятно

2020-10-12 10:06 UTC, Karambirov commented on src/services/date-formatter.js
> +    return `${dayOfWeek}, ${currentDate} ${currentMonth} ${hour}:${minutes}`;
Да, `dayOfMonth` будет лучше

2020-10-12 10:08 UTC, Karambirov submitted a review, later dismissed

2020-10-12 10:24 UTC, StayInLight approved these changes

2020-10-12 10:30 UTC, Karambirov approved these changes

2020-10-12 10:30 UTC, merged