(#33) Реализовал отображение погоды для полученного города
StayInLight/react-weather-app pull request #34
Opened 2020-10-13 22:35 UTC by StayInLight

Closes (#33)

2020-10-14 05:22 UTC, Karambirov requested changes

2020-10-14 05:22 UTC, Karambirov commented on src/components/search-bar/search-bar.jsx
> +          inputValue: '',
Зачем второй раз это устанавливать? Выше уже сделал тоже самое

2020-10-14 14:52 UTC, denkhis requested changes

2020-10-14 14:52 UTC, denkhis commented on src/components/search-bar/search-bar.jsx
> +          onChange={this.handleChange}
Почему нельзя сделать один метод из `handleSubmit` и `handleChange` и вызывать его на `onKeyDown` ?

2020-10-14 21:17 UTC, StayInLight commented on src/components/search-bar/search-bar.jsx
> +          inputValue: '',
Такое состояние для `input` устанавливается после нажатия enter. В первом случае я просто задаю поле `inputValue` для нашего `state`. Эта логика нужна для того, чтобы очистить поле после нажатия enter

2020-10-16 19:23 UTC, Karambirov approved these changes

2020-10-17 12:13 UTC, denkhis approved these changes

2020-10-17 12:13 UTC, merged