Реализация обработки ошибки запроса
StayInLight/react-weather-app pull request #36
Opened 2020-10-14 21:13 UTC by denkhis

Добавил отображение сообщения об ошибке и соответствующий эмоджи.

2020-10-15 05:10 UTC, Karambirov requested changes

2020-10-15 05:10 UTC, Karambirov commented on src/components/weather-card-content/weather-card-content.jsx
> +        hasError ? <div className="weather-card__content_message"><span>Введите правильное название города</span></div> : null
Зачем внутри div добавлять span? Одного из них будет достаточно

2020-10-15 05:10 UTC, Karambirov commented on src/components/weather-card/weaher-card.jsx
> +      hasError: '',
Если у переменной название звучит как вопрос, то она должна быть булевой.
Здесь должно быть либо значение `false`, либо сама переменная должна называться `error`.
В других местах тоже самое

2020-10-15 05:10 UTC, Karambirov commented on src/components/weather-card/weaher-card.jsx
> +          onInputChange={this.onInputChange}
Здесь параметры должны быть в том же порядке, как они объявлены внутри самого компонента

2020-10-15 05:11 UTC, Karambirov commented
Ещё посмотри лог билда и исправь ошибку, чтобы он стал зелёным

2020-10-15 13:23 UTC, StayInLight commented
У тебя ошибка в ci, проверь логи и исправь

2020-10-15 13:48 UTC, Karambirov requested changes
Надо, чтобы билд собрался

2020-10-15 16:00 UTC, Karambirov commented on src/components/weather-card-content/weather-card-content.jsx
> +          ) : null
Может лучше так?

```suggestion
          hasError 
            ? <span role="img" className="weather-card__content_emoji">&#128533;</span> 
            : null
```

2020-10-15 20:49 UTC, Karambirov requested changes

2020-10-15 20:49 UTC, Karambirov commented on src/components/weather-card-content/weather-card-content.jsx
> +  const { cityName, ...tempAndWeatherName } = weatherObject;
Зачем здесь коллекция для температуры и погоды? Почему нельзя это сделать отдельными параметрами?

2020-10-15 20:49 UTC, Karambirov commented on src/components/weather-card-content/weather-card-content.jsx
> +const EmojiAndTemperature = ({ weatherName, temperature }) => (
Почему этот компонент не в отдельном файле?
Вроде его можно переиспользовать, если появится необходимость показывать погоду в других режимах (на несколько дней, неделю и тому подобное)

2020-10-16 13:39 UTC, denkhis commented on src/components/weather-card-content/weather-card-content.jsx
> +  const { cityName, ...tempAndWeatherName } = weatherObject;
В данном случае это новый объект, в котором только два поля
`temperature`
`weatherName`

Так код смотрится немного чище, если пробрасывать в компонент этот объект

2020-10-16 13:49 UTC, Karambirov approved these changes

2020-10-16 16:02 UTC, StayInLight approved these changes

2020-10-16 16:02 UTC, tirakhimov commented on src/components/weather-card-content/weather-card-content.css
> +  margin-top: 10px;
Надо поправить верстку ошибки, текст ошибки должен быть сразу после поля. Размер шрифта ошибки меньше. Дату нужно скрывать как и хедер погода в ....

Также надо исправить `padding` для emoji

2020-10-16 16:02 UTC, tirakhimov commented on src/components/weather-card/weaher-card.jsx
> +      hasError: '',
Поле изначально false

2020-10-16 16:02 UTC, tirakhimov commented on src/components/weather-card-content/weather-card-content.jsx
> +const EmojiAndTemperature = ({ weatherName, temperature }) => (
Потому что это приватный компонент, который не будет использоваться нигде, кроме карточки

2020-10-16 16:02 UTC, tirakhimov commented on src/components/weather-card-content/weather-card-content.jsx
> +  const { cityName, ...tempAndWeatherName } = weatherObject;
Коллекция нужна, чтобы потом передать ее в пропсах другому компоненту, который отвечает за отрисовку. Не стоит передавать ему лишние свойства, поэтому используется такой синтаксис

2020-10-16 16:02 UTC, merged