(#46) Миграция инфраструктуры с JavaScript на Typescript
StayInLight/react-weather-app pull request #52
Opened 2020-10-28 20:18 UTC by StayInLight

Closes #46

2020-10-28 23:31 UTC, denkhis submitted a review, later dismissed

2020-10-29 09:28 UTC, Karambirov requested changes

2020-10-29 09:28 UTC, karambirov commented on package.json
> +    "@types/jest": "^26.0.15",
Почему добавился `Jest`? Он вместе с зависимостями подтянулся или ты собираешься написать тесты?

2020-10-29 09:28 UTC, karambirov commented on src/components/emoji-and-temperature/emoji-and-temperature.tsx
> +}
Этот тип стоит перенести выше, чтобы он был над интерфейсов. Так будет лучше читаться

2020-10-29 09:28 UTC, karambirov commented on src/components/emoji-and-temperature/emoji-and-temperature.tsx
>    const {weatherName, temperature} = tempAndWeatherName;
Рядом с фигурными скобками надо добавить пробелы

2020-10-29 09:28 UTC, karambirov commented on src/components/emoji-and-temperature/emoji-and-temperature.tsx
> +      <span
Почему `span` вместо настроенного элемента `Text`?

2020-10-29 09:28 UTC, karambirov commented on src/components/error-indicator/error-indicator.tsx
> +  errorLabel: string;
Соблюдай постоянство названий. Здесь стоит переименовать в `errorMessage`, как и в других местах. 
И в целом, label – это из iOS, в вебе так писать не нужно

2020-10-29 09:28 UTC, karambirov commented on src/components/navbar/navbar.tsx
> +        defaultSelectedKeys={["today"]}
А здесь точно нужен массив?

2020-10-29 09:28 UTC, karambirov commented on src/components/search-bar/search-bar.tsx
> +import React, { Component, KeyboardEvent, ChangeEvent }from 'react';
1. Перед `from` не хватает пробела.
2. Точно нужна эта деструктуризация, если ты импортируешь весь React?

2020-10-29 09:28 UTC, karambirov commented on src/components/search-bar/search-bar.tsx
> +  state: SearchBarState;
А стейт должен быть публичным?

2020-10-29 09:28 UTC, karambirov commented on src/components/weather-card-content/weather-card-content.tsx
>    const errorLabel = 'Такого города не существует';
Здесь и в других местах `errorMessage`

2020-10-29 09:28 UTC, Karambirov commented on src/components/weather-card-header/weather-card-header.tsx
> +  function headerSwitcher(): string {
Мне не очень нравится, что метод не содержит глагола. Выглядит как переменная какая-то.
Было бы лучше, если бы он назывался `setHeader()`. Так правильнее и четче передает суть в месте, где вызывается

2020-10-29 09:28 UTC, Karambirov commented on src/components/weather-card/weather-card.tsx
> +interface WeatherCardState {
`export` потерял

2020-10-29 09:28 UTC, Karambirov commented on src/components/weather-card/weather-card.tsx
> +      this.updateState()?.then(() => {
Почему здесь опциональное значение?

2020-10-29 09:28 UTC, Karambirov commented on src/components/weather-card/weather-card.tsx
> +  updateState(): Promise<void> | undefined {
Разве тут может быть `undefined `?

2020-10-29 09:28 UTC, Karambirov commented on src/components/weather-card/weather-card.tsx
> +    if (weatherObject.cityName) {
Какая-то JS-ная проверка. Если ты пишешь на TS и хочешь проверить, что опционал содержит значение, то проверяй, что `weatherObject.cityName !== null`

2020-10-29 09:28 UTC, Karambirov commented on src/components/weather-card/weather-card.tsx
> +        <Col span={9}>
Уверен, что нечетное число стоит использовать?

2020-10-29 09:28 UTC, Karambirov commented on src/index.tsx
> +import * as ReactDOM from 'react-dom';
Вот такие импорты не должны быть в других файла по аналогии с этим?

2020-10-29 09:28 UTC, Karambirov commented on src/react-app-env.d.ts
> +/// <reference types="react-scripts" />
Выглядит как файл, который нужно добавить в `.gitignore`, а отсюда удалить

2020-10-29 09:28 UTC, Karambirov commented on src/services/date-formatter.ts
> +  formatDate(): string {
Вот сюда на вход можно было бы передавать дату, чтобы форматтер всегда работал с актуальной датой.
Сейчас форматтер работает с той датой, которая установилась в конструкторе при создании форматтера. Это может быть проблемой.

Я бы удалил `private readonly date: Date;`, а в метод передал бы дату, а чтобы каждый раз её не передавать явно указал бы дефолтный параметр: 
```typescript
formatDate(date: Date = new Date()): string { ... };
```

2020-10-29 09:28 UTC, Karambirov commented on src/services/date-formatter.ts
> +    const minutes: number = this.date.getMinutes();
Ну и тогда здесь везде нужно будет удалить `this`

2020-10-29 09:28 UTC, Karambirov commented on src/services/networking-service.ts
> +type WeatherType = {
Тут тоже нужен `export`

2020-10-29 09:28 UTC, Karambirov commented on src/services/weather-service.ts
> +  constructor() {
Раз уж теперь можешь создавать приватные переменные, давай будет использовать конструктор правильно?
```typescript
constructor(networkingService: NetworkingService, emojiService: EmojiService) {
  this.networkingService = networkingService;
  this.emojiService = emojiService;
}
```

2020-10-29 09:28 UTC, Karambirov commented on src/services/weather-service.ts
> +  constructor() {
Опять же, чтобы улучшить архитектуру, но не переписывать много кода, можно добавить дефолтные значения: 

```typescript
constructor(
  networkingService: NetworkingService = new NetworkingService(), 
  emojiService: EmojiService = new EmojiService()
) {
  this.networkingService = networkingService;
  this.emojiService = emojiService;
}
```

Всё будет работать как и прежде, но архитектура станет лучше, а компонент тестируемым.

2020-10-29 09:28 UTC, Karambirov commented on src/services/weather-service.ts
> +  constructor() {
Подумай, где ещё можно применить такое решение)

2020-10-29 09:28 UTC, Karambirov commented on tsconfig.json
> +    "target": "es5",
Почему не ES6? В линтере ты используешь настройку `ecmaVersion: 2020`

2020-10-29 10:36 UTC, denkhis commented on src/components/emoji-and-temperature/emoji-and-temperature.tsx
> +      <span
На тег `Text` ругается Linter и Node CLI, уже несколько раз такое было у нас.

2020-10-29 11:03 UTC, Karambirov commented on src/components/emoji-and-temperature/emoji-and-temperature.tsx
> +      <span
@denkhis, может надо тогда с этой проблемой разобраться, а не костылить `span`? Мы же затащили дизайн систему, чтобы пользоваться ей. И типографика одна из важнейших частей.

2020-10-29 13:16 UTC, StayInLight commented on src/components/navbar/navbar.tsx
> +        defaultSelectedKeys={["today"]}
Да, так как выбранных ключей может быть много, там интерфейс, который ждет массив и TS ругается, если использовать строку

2020-10-29 13:18 UTC, StayInLight commented on src/components/search-bar/search-bar.tsx
> +import React, { Component, KeyboardEvent, ChangeEvent }from 'react';
Можно использовать React.KeyboardEvent и т.д., однако мне кажется читается лучше, если мы используем деструктуризацию.

2020-10-29 13:20 UTC, StayInLight commented on src/components/search-bar/search-bar.tsx
> +  state: SearchBarState;
![Screenshot 2020-10-29 at 16 19 34](https://user-images.githubusercontent.com/36644693/97578945-89dab280-1a02-11eb-9f48-87232c3a8d0c.png)
Мы не можем сделать его приватным, так как в классе родителе оно не приватное, однако его необходимо сделать только для чтения.

2020-10-29 14:20 UTC, StayInLight commented on src/index.tsx
> +import * as ReactDOM from 'react-dom';
В tsconfig есть поле в compilerOptions, которое позволяет писать импорты стандартным способом, однако для файла index.tsx почему-то не работает

2020-10-29 16:04 UTC, StayInLight commented on tsconfig.json
> +    "target": "es5",
`ecmaVersion` позволяет использовать фичи последнего стандарта JavaScript. Target показывает, в какую версию код будет транспилироваться бабелем, это нужно для поддержки старых браузеров.

2020-10-29 16:59 UTC, Karambirov requested changes

2020-10-29 16:59 UTC, Karambirov commented on src/components/weather-card-content/weather-card-content.tsx
> +  hasError?: Error;
has/is надо добавлять у булевых переменных, а тут просто должно быть `error?: Error`

2020-10-29 16:59 UTC, Karambirov commented on src/components/weather-card-header/weather-card-header.tsx
> +  hasError?: Error;
Здесь то же самое

2020-10-29 16:59 UTC, Karambirov commented on src/components/weather-card-header/weather-card-header.tsx
> +    if (hasError !== undefined) {
Почему `undefined`? Тут мой косяк, погуглил этот вопрос, должно быть:
```typescript
if (error) { ... }
```
Потому что такая проверка в TypeScript проверяет, что это не:
- null
- undefined
- NaN
- empty string ("")
- 0
- false

2020-10-29 16:59 UTC, Karambirov commented on src/components/weather-card/weather-card.tsx
> +  hasError?: Error;
Замени на `error`

2020-10-29 16:59 UTC, Karambirov commented on src/components/weather-card/weather-card.tsx
> -              hasError: true,
А здесь не нужно перед ошибкой занулить объект, чтобы избежать неправильного стейта?
```typescript
this.setState({
  weatherObject: {},
  error: error,
});
```
Или может вместо пустого объекта поставить `undefined`? (Хотя это вроде одно и то же?)

2020-10-30 10:18 UTC, Karambirov requested changes

2020-10-30 10:18 UTC, Karambirov commented on src/services/weather-service.ts
>    }
Из-за того, что строки длинные, так будет читаться лучше:
```typescript
constructor(
  networkingService: NetworkingService = new NetworkingService(),
  emojiService: EmojiService = new EmojiService()
) {
  this.networkingService = networkingService;
  this.emojiService = emojiService;
}
```

2020-10-30 10:41 UTC, denkhis commented on src/components/weather-card/weather-card.tsx
> -              hasError: true,
`Type 'undefined' is not assignable to type 'WeatherObject'`. 
Поэтому в данном случае возможно только "занулить" его.

2020-10-30 10:48 UTC, denkhis commented on src/components/weather-card/weather-card.tsx
> +  updateState(): Promise<void> | undefined {
Функция `updateState` ничего не возвращает, поэтому возможен `undefined` в случае, если `weatherObject.cityName` равен `undefined`. Иначе промис.

2020-10-30 10:49 UTC, denkhis commented on src/components/weather-card/weather-card.tsx
> +      this.updateState()?.then(() => {
Потому что `updateState` может вернуть `undefined`.

2020-10-30 11:14 UTC, Karambirov requested changes

2020-10-30 11:14 UTC, Karambirov commented on src/components/weather-card-header/weather-card-header.tsx
> +    if (error !== undefined) {
Здесь надо убрать проверку на `undefined`, чтобы было только `if (error) { ... }`.
Выше написал почему так

2020-10-30 12:36 UTC, Karambirov approved these changes

2020-10-30 12:38 UTC, merged