(#1) Создал Readme
StayInLight/react-weather-app pull request #53
Opened 2020-10-28 21:12 UTC by StayInLight

Closes #1

2020-10-28 22:41 UTC, denkhis approved these changes, later dismissed

2020-10-29 08:16 UTC, Karambirov requested changes
Ещё неплохо бы завести задачу на деплой на Netlify, а потом добавить ссылку в описании в самом верху

2020-10-29 08:16 UTC, Karambirov commented on README.md
> +- [x] Приложение отображает погоду в разных городах.
Допиши, что данные получает с OpenWeatherMap API

2020-10-29 08:16 UTC, Karambirov commented on README.md
> +- [x] Приложение написано на библиотеке ([React](https://github.com/facebook/react)).
Слово "библиотеке" удали. Это не библиотека, а фреймворк

2020-10-29 08:16 UTC, Karambirov commented on README.md
> +- [x] Приложение отображает погоду в разных городах.
Тоже ссылку на API добавь как в разделе с технологиями

2020-10-29 08:16 UTC, Karambirov commented on README.md
> +- [x] Приложение использует библиотеку React UI компонентов ([Ant Design](https://github.com/ant-design/ant-design)).
Здесь "React" удали. Ant Design доступен много где ещё

2020-10-29 08:16 UTC, Karambirov commented on README.md
> +Для запуска введите следующие команды в терминале:
Тут нужно дописать, что для установки требуется GitHub CLI и npm. Иначе оно просто не заведется у многих

2020-10-29 08:18 UTC, Karambirov commented on README.md
> +- [x] Приложение написано на библиотеке ([React](https://github.com/facebook/react)).
Во всем разделе технологий поудаляй скобки вокруг ссылок. Выглядит странно с ними

2020-10-29 12:57 UTC, StayInLight commented on README.md
> +- [x] Приложение написано на библиотеке ([React](https://github.com/facebook/react)).
<img width="691" alt="Screenshot 2020-10-29 at 15 57 25" src="https://user-images.githubusercontent.com/36644693/97576618-71b56400-19ff-11eb-8831-a19eac541ee0.png">
Это вечный холивар, однако официальный сайт гласит, что это все-таки библиотека.

2020-10-29 13:03 UTC, Karambirov commented on README.md
> +- [x] Приложение написано на библиотеке ([React](https://github.com/facebook/react)).
Предлагаю не ввязывать в него и обойти вообще без этих слов)
Пусть будет `Приложение написано на React`

2020-10-29 15:10 UTC, Karambirov commented on README.md
> +- [x] Данные погоды получаются с API [OpenWeather](https://openweathermap.org/api).
Не дописал название `OpenWeatherMap`

2020-10-29 15:27 UTC, Karambirov approved these changes

2020-10-29 15:31 UTC, merged