Add redux
StayInLight/react-weather-app pull request #65
Opened 2020-11-06 14:35 UTC by denkhis

2020-11-06 16:10 UTC, Karambirov requested changes

2020-11-06 16:10 UTC, karambirov commented on src/actions/actions.ts
> +import {CLEAN_CITY_NAME, ERROR, FETCH_WEATHER, SEARCH_CITY} from '../constants/action-constants';
В какой-то момент перестали в проекте соблюдать кодстайл и начали писать без пробелов в фигурных скобках. Проверь во всем проекте, где нет пробелов и добавь их.
Чтобы было так: `{ Dispatch }`

2020-11-06 16:10 UTC, karambirov commented on src/actions/actions.ts
> +  return weatherService.getWeatherForToday(inputValue)
А точно хорошая идея создавать экземпляр сервиса здесь вместо передачи его из вне?
Так принято во фронтенде или это ты так решил сделать?

2020-11-06 16:10 UTC, Karambirov commented on src/components/navbar/navbar.tsx
> +          <Text style={{color: "white"}} className="navbar__logo-text">Weather App</Text>
Зачем здесь и класс, и стиль? Надо удалить стиль

2020-11-06 16:10 UTC, Karambirov commented on src/components/search-bar/search-bar.tsx
> +    if(props.inputValue) {
После `if` пробел надо добавить

2020-11-06 16:10 UTC, Karambirov commented on src/components/search-bar/search-bar.tsx
> +import {SearchBarProps} from '../../interfaces/SearchBarProps';
А почему ты решил пропсы выносить в отдельный файл? Они имеют смысл только рядом с компонентом. Интерфейсы выносят в отдельные файлы, когда они используются в нескольких местах

2020-11-06 16:10 UTC, Karambirov commented on src/reducers/reducer.ts
> +      if (action.payload !== undefined) {
Должно быть просто `if (action.payload)`. В других местах проекта тоже нужно исправить везде

2020-11-06 22:29 UTC, denkhis commented on src/actions/actions.ts
> +import {CLEAN_CITY_NAME, ERROR, FETCH_WEATHER, SEARCH_CITY} from '../constants/action-constants';
Видимо, сбились настройки линтера, потому что раньше он ругался. Поправлю.

2020-11-06 22:31 UTC, denkhis commented on src/actions/actions.ts
> +  return weatherService.getWeatherForToday(inputValue)
Не совсем понял. Ты думаешь, что правильнее будет передать в `actions.ts` экземпляр класса?

2020-11-07 08:39 UTC, Karambirov commented on src/actions/actions.ts
> +  return weatherService.getWeatherForToday(inputValue)
Да, создавать скрытые зависимости внутри всегда плохо. Ты поймешь это на примере, когда будешь писать тесты

2020-11-08 16:41 UTC, denkhis commented on src/components/search-bar/search-bar.tsx
> +import {SearchBarProps} from '../../interfaces/SearchBarProps';
Это касается всех компонентов ?

2020-11-08 18:19 UTC, Karambirov commented on src/components/search-bar/search-bar.tsx
> +import {SearchBarProps} from '../../interfaces/SearchBarProps';
Такая логика касается все интерфейсов. Если нигде за пределами одного файла он использоваться не будет, то выносить интерфейс в отдельный файл не надо

2020-11-08 18:20 UTC, Karambirov approved these changes

2020-11-08 18:46 UTC, StayInLight approved these changes

2020-11-09 11:40 UTC, merged