Adaptive layout
StayInLight/react-weather-app pull request #67
Opened 2020-11-06 22:28 UTC by denkhis

2020-11-07 08:47 UTC, Karambirov approved these changes
Всё отлично, но не мерджи пока redux и исправления линтера не будут в `main`

2020-11-07 17:59 UTC, Karambirov requested changes

2020-11-07 17:59 UTC, Karambirov commented on src/components/navbar/navbar.css
> +  color: #fff !important;
Выглядит как костыль, тебе не кажется?

2020-11-07 20:26 UTC, StayInLight commented on src/components/navbar/navbar.css
> +  color: #fff !important;
Там трабл в том, что не смог найти, как поменять цвет текста в стилях. Стили библиотеки переписывают наши, поэтому приходится использовать !important

2020-11-08 18:17 UTC, Karambirov commented
Нужно исправить конфликты

2020-11-08 18:17 UTC, Karambirov approved these changes

2020-11-08 18:53 UTC, StayInLight requested changes

2020-11-08 18:53 UTC, StayInLight commented on src/components/search-bar/search-bar.tsx
> +    <Row className="" justify="center" align="middle">
Почему пустой className?

2020-11-09 12:03 UTC, closed without merging